# Generated by Django 5.0 on 2023-12-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['is_active', 'is_staff'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
