# Generated by Django 5.0 on 2023-12-25 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='locale',
            field=models.CharField(blank='FI', choices=[('FI', 'Finnish'), ('EN', 'English'), ('SV', 'Swedish'), ('ES', 'Spanish')], default='FI', max_length=5, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Photo Url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo upload'),
        ),
    ]
