# Generated by Django 5.0 on 2023-12-29 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_page',
            options={'verbose_name': 'about', 'verbose_name_plural': 'abouts'},
        ),
        migrations.AlterField(
            model_name='about_page',
            name='content',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Mood'),
        ),
    ]
